[mega]
type = mega
user = emilypeterson30@mail.findmeghana.org
pass = AIjpeMEdPQWNTQHR6YYDYjcEoGFSOGHASO5DjwkHcXUW7iDLFg
session_id = YHpE8zZFzThFIYjGGm44xFcyUGl1YWtCWlE4_HnRwxFodO1IlI4aFoyFUg
master_key = s6SFGB0f4UZk7VYPwK/k3A==
endpoint = https://eu.api.mega.co.nz/
